import React from "react";
import { Document, Page, View, Text, Image, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    padding: 24,
    backgroundColor: "#fff",
  },
  logoContainer: {
    alignItems: "center",
    marginBottom: 12,
    minHeight: 60,
  },
  logo: {
    height: 50,
    objectFit: "contain",
    marginBottom: 8,
  },
  sectionTitle: {
    fontWeight: "bold",
    fontSize: 13,
    marginTop: 12,
    marginBottom: 6,
  },
  table: {
    display: "table",
    width: "auto",
    marginBottom: 8,
  },
  row: {
    flexDirection: "row",
  },
  cellLabel: {
    width: "30%",
    fontWeight: "bold",
    padding: 2,
    borderRight: "1pt solid #eee",
    backgroundColor: "#f5f5f5",
  },
  cellValue: {
    width: "70%",
    padding: 2,
  },
  signature: {
    marginTop: 18,
    fontStyle: "italic",
  },
  small: {
    fontSize: 9,
    color: "#888",
  },
});

function TableRow({ label, value }) {
  return (
    <View style={styles.row}>
      <Text style={styles.cellLabel}>{label}</Text>
      <Text style={styles.cellValue}>{value}</Text>
    </View>
  );
}

export default function WarrantyClaimPDF({ form, logo }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Logo */}
        <View style={styles.logoContainer}>
          {logo && <Image style={styles.logo} src={logo} />}
        </View>
        <Text style={{ fontWeight: "bold", fontSize: 16, textAlign: "center", marginBottom: 10 }}>
          WARRANTY CLAIM
        </Text>
        {/* Company Detail */}
        <Text style={styles.sectionTitle}>Company Detail</Text>
        <View style={styles.table}>
          <TableRow label="Company" value={form.company} />
          <TableRow label="Contact" value={form.contact} />
          <TableRow label="Address" value={form.address} />
          <TableRow label="Phone" value={form.phone} />
          <TableRow label="City" value={form.city} />
          <TableRow label="State" value={form.state} />
          <TableRow label="Zip" value={form.zip} />
        </View>
        {/* Homeowner Detail */}
        <Text style={styles.sectionTitle}>Homeowner Detail</Text>
        <View style={styles.table}>
          <TableRow label="Name" value={form.homeowner} />
          <TableRow label="Phone" value={form.homeownerPhone} />
          <TableRow label="Address" value={form.homeownerAddress} />
          <TableRow label="City" value={form.homeownerCity} />
          <TableRow label="State" value={form.homeownerState} />
          <TableRow label="Zip" value={form.homeownerZip} />
        </View>
        {/* Product Detail */}
        <Text style={styles.sectionTitle}>Product Detail</Text>
        <View style={styles.table}>
          <TableRow label="Item" value={form.item} />
          <TableRow label="Model" value={form.model} />
          <TableRow label="Serial #" value={form.serial} />
          <TableRow label="Brand" value={form.brand} />
          <TableRow label="Date Installed" value={form.dateInstalled} />
          <TableRow label="Reason of Warranty" value={form.reason} />
        </View>
        <View style={styles.signature}>
          <Text>Signature: {form.signature}</Text>
        </View>
        {/* For internal use only */}
        <Text style={styles.sectionTitle}>For internal use only</Text>
        <View style={styles.table}>
          <TableRow label="Failed Part #" value={form.failedPart} />
          <TableRow label="New Part #" value={form.newPart} />
          <TableRow label="CM # Failed Part" value={form.cmFailedPart} />
          <TableRow label="SO # Repl Part" value={form.soReplPart} />
          <TableRow label="Failed Part Serial #" value={form.failedPartSerial} />
          <TableRow label="New Part Serial #" value={form.newPartSerial} />
          <TableRow label="Unit SO#" value={form.unitSO} />
          <TableRow label="Request Received by" value={form.requestReceivedBy} />
          <TableRow label="Received on" value={form.receivedOn} />
        </View>
        <Text style={styles.small}>Generated by Warranty Claim System</Text>
      </Page>
    </Document>
  );
}
